### ISSUE TITLE
72 but love your tweaks please read

### ISSUE THREAD

**Issue by cohiba55555** [tomaszpoliszuk/ActivatorListenerForPowercuff#2]
Iv got Powercuff but can’t figure where or how to download you activator listener deb file in github! Can you DM ME IT? I have Filza, ReProvision and Altstore on my IPhone X iOS 13.4.1. Googled but can’t find exact method that works. Any help to download a deb to my iPhone would be greatly appreciated. Be safe Hank

**Comment by tomaszpoliszuk** [comment]
It's deb file from [releases page](https://github.com/tomaszpoliszuk/ActivatorListenerForPowercuff/releases) - [direct link to that deb file](https://github.com/tomaszpoliszuk/ActivatorListenerForPowercuff/releases/download/1.0.1/com.tomaszpoliszuk.activatorlistenerforpowercuff_1.0.1_iphoneos-arm.deb).

**Comment by cohiba55555** [comment]
Thanks that worked great tweak be safe!
