### ISSUE TITLE
Request : Remain LPM toggle

### ISSUE THREAD

**Issue by CySxL** [tomaszpoliszuk/ActivatorListenerForPowercuff#4]
As title, I wanna remain the toggle state on of Only In Low Power Mode in Powercuff's setting.

Means it won't be interfered by other Activator actions assigned.  

Or maybe create a new listener for the toggle.

Thanks for all your hard work !!
I love all of ur Controller and Listener series !!
They are all so useful !!

**Comment by tomaszpoliszuk** [comment]
There is one already created exactly for this - [Low Power Mode Events for Activator](http://cydia.saurik.com/package/com.tomaszpoliszuk.lowpowermodeeventsforactivator/) - this way you can set Activator Listener For Powercuff (or any other listener) to anything you want when changing Low Power mode - let me know if this help with your issue.

(I'm glad you like my tweaks - thanks!)

**Comment by CySxL** [comment]
Your tweaks are all great 👍:) 

Btw I know the Low Power Mode Events for Activator but it can't fit my workaround tho haha.


My workaround is :
using Activator to set automatically enable LPM while in lockscreen and disable LPM while unlock device.
and also let Powercuff(moderate) enable Only In Low Power Mode.

I wanna set Activator listener for powercuff to disable Powercuff (Throttling set to None) while in lockscreen and connecting to charger, and enable Powercuff as moderate state while in lockscreen but disconnect the charger.

But the result is Powercuff throttling will stay at "moderate" even if I unlock my device, guess that's caused by the "Only In LPM" toggle is disabled in Powercuff.

**Comment by tomaszpoliszuk** [comment]
That what you described seems like happens because of issue #3 - I'm closing this issue but feel free to reopen it if it didn't solved your issue.
